### ISSUE TITLE
Missing dependency GLMHighlighterTextStylerDecorator in Pharo 9

### ISSUE THREAD

**Issue by StewMacLean** [mumez/SIXX#9]
When loading I found that GLMHighlighterTextStylerDecorator has been removed in Pharo 9

The workaround was to ignore the error and return nil to continue loading.

This worked for me as I just needed the core serialisation to convert objects from VisualWorks.

Thanks for this functionality - saved me a heap of "reentry"!

**Comment by mumez** [comment]
Thank you for your report.
The warning is probably related to the prerequisite XMLParser. I'll fix it soon.

**Comment by mumez** [comment]
I've made a pull request. It will be merged after testing. 
https://github.com/mumez/SIXX/pull/12

**Comment by mumez** [comment]
Now tests are all green! Please try the latest master (v0.5.3)
![2022-04-01 22_28_59-C__Users_ume_Documents_Pharo_images_sixx_sixx image](https://user-images.githubusercontent.com/705350/161273714-d4bd8045-e47f-4307-8526-17340034e528.png)
.

**Comment by mumez** [comment]
Now close the issue. Please let me know if there any problems.

**Comment by StewMacLean** [comment]
Thanks Masashi for developing this package and this fix.

It saved me a lot of time exporting some objects from VisualWorks to Pharo!
Thanks!

I did notice that you have done some work with the Objectivity graph
database. I don't have a requirement for a database at the moment, but when
I was looking at developing a business application I did enquire whether
they still had Smalltalk bindings. Unfortunately, they no longer supported
it.

Do you know if they have changed and will support Smalltalk/Pharo?

Cheers,

Stewart

**Comment by mumez** [comment]
Unfortunately, I'm not sure Objectivity/Smalltalk is still supported by Objectivity/DB. 
It had nice declarative relationships support, and I liked it a lot. However, it did not gain popularity.

If you are looking for a graph database, Neo4j will be a good candidate. 

I've developed some connectors for Pharo.
https://github.com/mumez/Neo4reSt (REST connector)
https://github.com/mumez/SCypherGraph (FFI connector)

Neo4reSt would be easily ported to VW, since it only relies on http client.

If you prefer more orthgonal persistence, I recommend GemStone/S. 
Now they offer a starter plan, and it is enough for small applications.
https://gemtalksystems.com/licensing/

**Comment by StewMacLean** [comment]
Hey thanks for this - I'm currently using Fuel as my object graphs are
small and I load them in entirety.

However, this looks very useful for a persistence back end for bigger data
sets.

ORM to be avoided at all costs!

Cheers,

Stewart
